// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	status "github.com/mhconradt/proto/status"
	user "github.com/mhconradt/proto/user"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserRequest struct {
	Id                   int32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GetMask              *field_mask.FieldMask `protobuf:"bytes,2,opt,name=get_mask,json=getMask,proto3" json:"get_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserRequest) GetGetMask() *field_mask.FieldMask {
	if m != nil {
		return m.GetMask
	}
	return nil
}

type GetUserResponse struct {
	User                 *user.User     `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               *status.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type CreateUserRequest struct {
	User                 *user.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	User                 *user.User     `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               *status.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *user.User            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *user.User     `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               *status.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{5}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type DeactivateUserRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeactivateUserRequest) Reset()         { *m = DeactivateUserRequest{} }
func (m *DeactivateUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeactivateUserRequest) ProtoMessage()    {}
func (*DeactivateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{6}
}

func (m *DeactivateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeactivateUserRequest.Unmarshal(m, b)
}
func (m *DeactivateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeactivateUserRequest.Marshal(b, m, deterministic)
}
func (m *DeactivateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeactivateUserRequest.Merge(m, src)
}
func (m *DeactivateUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeactivateUserRequest.Size(m)
}
func (m *DeactivateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeactivateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeactivateUserRequest proto.InternalMessageInfo

func (m *DeactivateUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeactivateUserResponse struct {
	User                 *user.User     `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               *status.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeactivateUserResponse) Reset()         { *m = DeactivateUserResponse{} }
func (m *DeactivateUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeactivateUserResponse) ProtoMessage()    {}
func (*DeactivateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{7}
}

func (m *DeactivateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeactivateUserResponse.Unmarshal(m, b)
}
func (m *DeactivateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeactivateUserResponse.Marshal(b, m, deterministic)
}
func (m *DeactivateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeactivateUserResponse.Merge(m, src)
}
func (m *DeactivateUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeactivateUserResponse.Size(m)
}
func (m *DeactivateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeactivateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeactivateUserResponse proto.InternalMessageInfo

func (m *DeactivateUserResponse) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *DeactivateUserResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "users.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "users.GetUserResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "users.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "users.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "users.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "users.UpdateUserResponse")
	proto.RegisterType((*DeactivateUserRequest)(nil), "users.DeactivateUserRequest")
	proto.RegisterType((*DeactivateUserResponse)(nil), "users.DeactivateUserResponse")
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea) }

var fileDescriptor_030765f334c86cea = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xdf, 0x8b, 0x13, 0x31,
	0x10, 0xc7, 0xe9, 0x62, 0xef, 0x64, 0x16, 0x2a, 0x17, 0xb9, 0xb3, 0x2e, 0x8a, 0x65, 0x5f, 0xee,
	0x10, 0x2e, 0x0b, 0x15, 0x41, 0xd4, 0x17, 0x51, 0xf4, 0xe9, 0x5e, 0x56, 0x8a, 0x8f, 0xb2, 0x3f,
	0xa6, 0x69, 0x68, 0x37, 0x89, 0x9b, 0xac, 0xe8, 0x3f, 0xe2, 0xdf, 0x2b, 0x9b, 0xc4, 0xee, 0x76,
	0x5b, 0xa5, 0x08, 0x7d, 0x69, 0x9a, 0xe4, 0xf3, 0x9d, 0x99, 0x6f, 0x66, 0x5a, 0x08, 0x1b, 0x8d,
	0xb5, 0xa6, 0xaa, 0x96, 0x46, 0x92, 0xb1, 0xdd, 0x44, 0xcf, 0x98, 0x94, 0x6c, 0x83, 0x89, 0x3d,
	0xcc, 0x9b, 0x65, 0x62, 0x78, 0x85, 0xda, 0x64, 0x95, 0x72, 0x5c, 0x34, 0x1b, 0x02, 0x4b, 0x8e,
	0x9b, 0xf2, 0x6b, 0x95, 0xe9, 0xb5, 0x27, 0x5e, 0x33, 0x6e, 0x56, 0x4d, 0x4e, 0x0b, 0x59, 0x25,
	0x5c, 0x2c, 0x65, 0xbe, 0x91, 0x3f, 0xa4, 0x42, 0xe1, 0x24, 0xc5, 0x2d, 0x43, 0x71, 0xcb, 0x64,
	0x5d, 0x25, 0x52, 0x19, 0x2e, 0x85, 0x4e, 0xda, 0x8d, 0xd7, 0xd2, 0x9e, 0xb6, 0x5a, 0x15, 0x52,
	0xd4, 0x59, 0x69, 0x9c, 0x30, 0xd1, 0x26, 0x33, 0x8d, 0xf6, 0x8b, 0xe7, 0x9f, 0xff, 0x83, 0x6f,
	0x0d, 0xd9, 0x0f, 0xc7, 0xc6, 0x5f, 0x60, 0xf2, 0x09, 0xcd, 0x42, 0x63, 0x9d, 0xe2, 0xb7, 0x06,
	0xb5, 0x21, 0x13, 0x08, 0x78, 0x39, 0x1d, 0xcd, 0x46, 0x37, 0xe3, 0x34, 0xe0, 0x25, 0x79, 0x09,
	0xf7, 0x19, 0x1a, 0xeb, 0x65, 0x1a, 0xcc, 0x46, 0x37, 0xe1, 0x3c, 0xa2, 0xce, 0x2e, 0xfd, 0x63,
	0x97, 0x7e, 0x6c, 0xed, 0xde, 0x65, 0x7a, 0x9d, 0x9e, 0x33, 0x34, 0xed, 0x97, 0x78, 0x0d, 0x0f,
	0xb6, 0x81, 0xb5, 0x92, 0x42, 0x23, 0xb9, 0x86, 0x7b, 0x6d, 0x66, 0x1b, 0x3b, 0x9c, 0x3f, 0xa4,
	0x8a, 0x0b, 0xa6, 0xa4, 0x60, 0xd4, 0xd6, 0x63, 0x51, 0x0b, 0x90, 0x04, 0xce, 0x9c, 0x21, 0x9f,
	0xf0, 0x51, 0x87, 0x7a, 0xa3, 0x9f, 0xed, 0x92, 0x7a, 0x2c, 0x7e, 0x0b, 0x17, 0xef, 0x6b, 0xcc,
	0x0c, 0xf6, 0x8d, 0x1c, 0x9b, 0x2e, 0x16, 0x40, 0xfa, 0xea, 0x93, 0x57, 0xfb, 0x13, 0x2e, 0x16,
	0xaa, 0xfc, 0xcf, 0x6a, 0xc9, 0x1b, 0x08, 0x1b, 0xab, 0x3e, 0xb6, 0x25, 0xe0, 0x70, 0xdb, 0x15,
	0x01, 0xa4, 0x9f, 0xfa, 0xe4, 0x56, 0xaf, 0xe1, 0xf2, 0x03, 0x66, 0x85, 0xe1, 0xdf, 0x07, 0x76,
	0x07, 0x53, 0x16, 0xd7, 0x70, 0x35, 0x04, 0x4f, 0x5d, 0xdc, 0xfc, 0x57, 0x00, 0xe3, 0x56, 0xaf,
	0xc9, 0x2b, 0x38, 0xf7, 0xc3, 0x4a, 0x2e, 0xa9, 0xfb, 0x03, 0xd8, 0xfd, 0x55, 0x44, 0x57, 0xc3,
	0x63, 0x5f, 0xdd, 0x3b, 0x80, 0x6e, 0x76, 0xc8, 0xd4, 0x53, 0x7b, 0xc3, 0x18, 0x3d, 0x3e, 0x70,
	0xd3, 0x85, 0xe8, 0x7a, 0xb2, 0x0d, 0xb1, 0x37, 0x21, 0xdb, 0x10, 0x07, 0x1a, 0x78, 0x07, 0x93,
	0xdd, 0xd7, 0x23, 0x4f, 0x3c, 0x7c, 0xf0, 0xf5, 0xa3, 0xa7, 0x7f, 0xb9, 0x75, 0xe1, 0xf2, 0x33,
	0x3b, 0x45, 0x2f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x3f, 0x03, 0xdd, 0x0c, 0x05, 0x00,
	0x00,
}
